#!/bin/bash


#intall i3wm

echo "Ingrese nombre de usuario:"

read user

#install i3

apt-get install i3 -y

i3-config-wizard

mkdir /home/$user/i3install.temp

#controladores de media keys

apt-get install pactl -y

cd i3install.temp

wget https://github.com/acrisci/playerctl/releases/download/v0.5.0/playerctl-0.5.0_amd64.deb

dpkg -i playerctl-0.5.0_amd64.deb

#wallpaper

mkdir /home/$user/Pictures/.wallpaper

cd /home/$user/Pictures/.wallpaper && wget http://wallpapercave.com/wp/hc11meW.jpg

mv /home/$user/Pictures/.wallpaper/hc11meW.jpg /home/$user/Pictures/.wallpaper/wallpaper.jpg

apt-get install feh -y

feh --bg-scale /home/$user/Pictures/.wallpaper/wallpaper.jpg

#fonts awesome

cd /home/$user/i3install.temp

wget https://github.com/FortAwesome/Font-Awesome/archive/v4.7.0.zip

unzip v4.7.0.zip

mkdir /home/$user/.fonts

mv /home/$user/i3install.temp/Font-Awesome-4.7.0/fonts/fontawesome-webfont.ttf /home/$user/.fonts

cd /home/$user/i3install.temp

wget https://github.com/supermarin/YosemiteSanFranciscoFont/archive/master.zip

unzip YosemiteSanFranciscoFont-master.zip

mv /home/$user/i3install.temp/YosemiteSanFranciscoFont-master/*.ttf /home/$user/.fonts

apt-get install lxappearance

echo "Abrir lxappearance y cambiar tamanho de la letra"

read nada

echo "Cambiar la fuete a System San Francisco Display 10"

read nada

nano /home/$user/.gtkrc-2.0

read nada

nano /home/$user/.config/gtk-3.0/settings.i3install

read nada

apt-get install comptom -y

apt-get install i3blocks -y

cp /etc/i3blocks.conf /home/$user/.i3/

rm -rf /home/$user/i3install.temp
